learning_user/basicapp/urls.py
from django.urls import path
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/', views.user_login, name='user_login'),
    ]

learning_user/learning_user/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('basicapp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/', views.special,name='special'),
]

learning_user/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

learning_user/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_user/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request,'basicapp/index.html')
@login_required
def special(request):
    return HttpResponse('you are Login , nice!')

@login_required 
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method =="POST":
        user_form =UserForm(data=request.POST)
        profile_form =UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()


            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic =request.FILES['profile_pic']
            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'basicapp/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})


def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account is not active')
        else:
            print('someone tried to login and failed')
            print("username: {} and password: {} ".format(username,password))
            return HttpResponse('invalid login details')

    else:
        return render(request,'basicapp/login.html',{})
        

    

learning_user/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-primary navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>

                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a href="{% url 'basicapp:register' %}">Register</a></li>

                {% if user.is_authenticated %}
                 <li> <a class="navbar-link" href="{% url 'logout' %}">logout</a> </li>

                {% else %}
                 <li><a class="navbar-link" href="{% url 'basicapp:user_login' %}">Login</a></li>
                {% endif %}

            </ul>

        </div>

    </nav>
    {% block body_block %}
    {% endblock %}

    
</body>
</html>

learning_user/templates/basicapp/index.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
{%block body_block%}
<div class="jumbotron">
    <h1>Welcome to home page</h1>

</div>

{% endblock %}

learning_user/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}

{% block body_block %}
<div class="jumbotron">
    <h1>please Login:</h1>
    <form action="{% url 'basicapp:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password</label>
        <input type="password" name="password">
        <input type="submit" class="btn btn-primary" value="LogIn">

    </form>


</div>

{% endblock %}

learning_user/templates/basicapp/registration.html
{% extends 'basicapp/base.html' %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}